# Generated by Django 5.2.10 on 2026-02-03 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_userhierarchy_group"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingDeletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        help_text="Admin who requested the deletion",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deletion_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Superuser who approved/rejected",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_deletions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_hierarchy",
                    models.ForeignKey(
                        help_text="The UserHierarchy record to be deleted",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_deletions",
                        to="accounts.userhierarchy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pending Deletion",
                "verbose_name_plural": "Pending Deletions",
                "ordering": ["-requested_at"],
            },
        ),
    ]
