# Generated by Django 5.2.10 on 2026-02-03 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_pendingdeletion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OperationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[("EXPORT", "Export"), ("IMPORT", "Import/Migrate")],
                        max_length=20,
                    ),
                ),
                (
                    "target_db",
                    models.CharField(help_text="Database involved", max_length=255),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "params",
                    models.JSONField(help_text="Job parameters needed for execution"),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("EXECUTED", "Executed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("admin_approved", models.BooleanField(default=False)),
                ("superuser_approved", models.BooleanField(default=False)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="operation_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who made the final approval decision",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_operations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductionDatabase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("host", models.CharField(max_length=255)),
                ("port", models.IntegerField(default=3306)),
                ("name", models.CharField(help_text="Database Name", max_length=255)),
                ("is_production", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Production Database",
                "verbose_name_plural": "Production Databases",
                "unique_together": {("host", "port", "name")},
            },
        ),
    ]
