# Generated by Django 5.2.10 on 2026-02-03 11:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_operationrequest_productiondatabase"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productiondatabase",
            options={
                "verbose_name": "Production Host",
                "verbose_name_plural": "Production Hosts",
            },
        ),
        migrations.AlterUniqueTogether(
            name="productiondatabase",
            unique_together={("host", "port")},
        ),
        migrations.RemoveField(
            model_name="productiondatabase",
            name="name",
        ),
    ]
