# Generated by Django 5.2.10 on 2026-02-26 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_productiondatabase_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationrequest",
            name="requester_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Group of the user who made this request (for admin-level filtering)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="operation_requests",
                to="accounts.group",
            ),
        ),
    ]
