# Generated by Django 5.2.10 on 2026-03-02 04:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_databasehost"),
    ]

    operations = [
        migrations.AddField(
            model_name="databasehost",
            name="db_password",
            field=models.CharField(
                blank=True,
                help_text="Pre-fill database password for this host",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="databasehost",
            name="db_username",
            field=models.CharField(
                blank=True,
                help_text="Pre-fill database username for this host",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="databasehost",
            name="label",
            field=models.CharField(
                help_text="Short key shown in UI, e.g. 'db_demo' or 'db_production'",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="databasehost",
            name="notes",
            field=models.CharField(
                blank=True,
                help_text="Optional description, e.g. 'Demo server - Singapore'",
                max_length=255,
            ),
        ),
    ]
