# Generated by Django 5.2.10 on 2026-03-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_databasehost_db_password_databasehost_db_username_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productiondatabase",
            name="hardcoded_dbs",
            field=models.TextField(
                blank=True,
                help_text="Comma-separated list of database names to show in the migration dropdown.",
                null=True,
            ),
        ),
    ]
